### ISSUE TITLE
[FEATURE REQUEST] Add local database

### ISSUE THREAD

**Issue by esQmo** [FabioXimenes/FlutterMovies#3]
Are you considering adding support for local caching with SQLite, Floor, etc? Would be awesome if you can add support for offline movies browsing. I just started learning Flutter, I'm not enough confident to implement such complex things :D

**Comment by esQmo** [comment]
Found this lib: https://pub.dev/packages/brick_offline_first
It may help. 
Peace

**Comment by FabioXimenes** [comment]
It's something that a real project must consider. I am currently working on other projects that are really time-consuming. So I don't have any plans to add support for this kind of feature, maybe in the future. I am also new to flutter, have been playing with it for 2-3 weeks now. If you implement this feature, let me know and make a pull request. I will definitely appreciate it.

**Comment by esQmo** [comment]
Started reading some tutorials, I think I'll be able to implement it. I'll let you know when I'm done.
